---
- name: Install the AWSCLI package
  apt:
    name: "awscli"
    state: "present"
  tags: [ never, infra ]

- include_tasks: "create_cfgs.yml"
  loop: "{{ awscli_users | default([]) }}"
  loop_control:
    loop_var: "user"
  tags: [ never, configs ]